name: ubi_vocab
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - jupyter
  - nltk=3.5
  - numpy=1.20.1
  - pip=21.0.1
  - pandas=1.2.1
  - pandera=0.6.2
  - plotly=4.14.3
  - pip=21.0
  - python=3.7
  - pytorch=1.6.0
  - pydantic=1.8.1
  - sentence-transformers=0.4.1
  - spacy=2.3.5
  - scipy=1.6.1
  - scikit-learn=0.24.1
  - transformers=4.4.2
  - torchvision=0.7.0
  - black=20.8

