name: ubi_vocab
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - jupyter
  - nltk=3.5
  - numpy=1.20.1
  - pip=21.0.1
  - pandas=1.2.1
  - pip=21.0
  - python=3.7
  - pytorch=1.6.0
  - torchvision=0.7.0
  - black=20.8
  - pip:
    - PyDictionary
